 # Open Global E-Commerce Sales Analytics & Customer Insights in Power BI
  https://app.powerbi.com/groups/me/reports/d036d9d4-c7e8-4456-9f10-d5d3118b29b9/794bf4a1dc8012651eaf?experience=power-bi

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [ ]:
data= pd.read_csv("/content/power bi retail Noon dataset.csv")
data

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,Discount_Applied,Total_Revenue,Payment_Method,Delivery_Time_Days,Customer_Rating
0,TXN1000,01-01-2023,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,0.04,257.76,PayPal,8,3.3
1,TXN1001,01-01-2023,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,0.05,3219.07,Credit Card,9,3.8
2,TXN1002,01-01-2023,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,0.13,340.67,Credit Card,14,1.5
3,TXN1003,01-01-2023,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,0.10,1038.09,Bank Transfer,11,1.6
4,TXN1004,01-01-2023,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,0.08,269.63,Credit Card,6,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,TXN50995,01-06-2026,CUST_20242,35,Female,Pakistan,Electronics,4K Smart TV,1100.15,2,0.13,1914.26,Credit Card,13,2.2
49996,TXN50996,01-06-2026,CUST_16159,34,Male,UK,Electronics,4K Smart TV,134.01,3,0.08,369.87,Credit Card,2,4.4
49997,TXN50997,01-06-2026,CUST_22746,40,Female,UK,Electronics,4K Smart TV,473.73,1,0.12,416.88,Bank Transfer,1,5.0
49998,TXN50998,01-06-2026,CUST_11975,37,Non-binary,Germany,Sports,Football,168.56,1,0.05,160.13,Crypto,10,3.0
49999,TXN50999,01-06-2026,CUST_5452,50,Male,Pakistan,Home & Kitchen,Air Fryer,254.14,3,0.11,678.55,Bank Transfer,2,3.8

In [ ]:
data.shape

(50000, 15)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      50000 non-null  object
 1   Date                50000 non-null  object
 2   Customer_ID         50000 non-null  object
 3   Customer_Age        50000 non-null  int64
 4   Gender              50000 non-null  object
 5   Location            50000 non-null  object
 6   Product_Category    50000 non-null  object
 7   Product_Name        50000 non-null  object
 8   Unit_Price          50000 non-null  float64
 9   Quantity            50000 non-null  int64
 10  Discount_Applied    50000 non-null  float64
 11  Total_Revenue       50000 non-null  float64
 12  Payment_Method      50000 non-null  object
 13  Delivery_Time_Days  50000 non-null  int64
 14  Customer_Rating     50000 non-null  float64
dtypes: float64(4), int64(3), object(8)
memory usage: 5.7+ MB

In [ ]:
data.isnull().sum()

Transaction_ID        0
Date                  0
Customer_ID           0
Customer_Age          0
Gender                0
Location              0
Product_Category      0
Product_Name          0
Unit_Price            0
Quantity              0
Discount_Applied      0
Total_Revenue         0
Payment_Method        0
Delivery_Time_Days    0
Customer_Rating       0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data["Date"] = pd.to_datetime(data["Date"], format="%d-%m-%Y")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      50000 non-null  object
 1   Date                50000 non-null  datetime64[ns]
 2   Customer_ID         50000 non-null  object
 3   Customer_Age        50000 non-null  int64
 4   Gender              50000 non-null  object
 5   Location            50000 non-null  object
 6   Product_Category    50000 non-null  object
 7   Product_Name        50000 non-null  object
 8   Unit_Price          50000 non-null  float64
 9   Quantity            50000 non-null  int64
 10  Discount_Applied    50000 non-null  float64
 11  Total_Revenue       50000 non-null  float64
 12  Payment_Method      50000 non-null  object
 13  Delivery_Time_Days  50000 non-null  int64
 14  Customer_Rating     50000 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(7)
memory usage: 5.7+ MB

In [ ]:
data["year"]= data["Date"].dt.year

In [ ]:
data["Quarter"] = data["Date"].dt.quarter

In [ ]:
data["Month_No"] = data["Date"].dt.month
data["Month"] = data["Date"].dt.month_name()

In [ ]:
data["Weekday"] = data["Date"].dt.strftime("%A")

In [ ]:
data.head()

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,Discount_Applied,Total_Revenue,Payment_Method,Delivery_Time_Days,Customer_Rating,year,Quarter,Month_No,Month,Weekday
0,TXN1000,2023-01-01,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,0.04,257.76,PayPal,8,3.3,2023,1,1,January,Sunday
1,TXN1001,2023-01-01,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,0.05,3219.07,Credit Card,9,3.8,2023,1,1,January,Sunday
2,TXN1002,2023-01-01,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,0.13,340.67,Credit Card,14,1.5,2023,1,1,January,Sunday
3,TXN1003,2023-01-01,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,0.10,1038.09,Bank Transfer,11,1.6,2023,1,1,January,Sunday
4,TXN1004,2023-01-01,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,0.08,269.63,Credit Card,6,4.5,2023,1,1,January,Sunday

In [ ]:
data["Revenue_Per_Unit"] = data["Total_Revenue"] / data["Quantity"]

In [ ]:
data["Delivery_Status"] = np.where(
    data["Delivery_Time_Days"] <= 5,
    "Fast Delivery",
    "Slow Delivery"
)

In [ ]:
data["Age_Group"] = pd.cut(
    data["Customer_Age"],
    bins=[18,25,35,45,55,65,100],
    labels=["18-25","26-35","36-45","46-55","56-65","65+"],
    include_lowest=True
)

In [ ]:
data.head()

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,...,Delivery_Time_Days,Customer_Rating,year,Quarter,Month_No,Month,Weekday,Revenue_Per_Unit,Delivery_Status,Age_Group
0,TXN1000,2023-01-01,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,...,8,3.3,2023,1,1,January,Sunday,85.920000,Slow Delivery,36-45
1,TXN1001,2023-01-01,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,...,9,3.8,2023,1,1,January,Sunday,1073.023333,Slow Delivery,26-35
2,TXN1002,2023-01-01,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,...,14,1.5,2023,1,1,January,Sunday,170.335000,Slow Delivery,36-45
3,TXN1003,2023-01-01,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,...,11,1.6,2023,1,1,January,Sunday,1038.090000,Slow Delivery,46-55
4,TXN1004,2023-01-01,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,...,6,4.5,2023,1,1,January,Sunday,134.815000,Slow Delivery,26-35

In [ ]:
data.isnull().sum()

Transaction_ID        0
Date                  0
Customer_ID           0
Customer_Age          0
Gender                0
Location              0
Product_Category      0
Product_Name          0
Unit_Price            0
Quantity              0
Discount_Applied      0
Total_Revenue         0
Payment_Method        0
Delivery_Time_Days    0
Customer_Rating       0
year                  0
Quarter               0
Month_No              0
Month                 0
Weekday               0
Revenue_Per_Unit      0
Delivery_Status       0
Age_Group             0
dtype: int64

In [ ]:
data.to_csv("Global_Ecommerce_Sales.csv",index=False)

In [ ]:
from google.colab import files
files.download("Global_Ecommerce_Sales.csv")